/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_threes;

import java.awt.GridLayout;
import java.util.Random;

/**
 *
 * @author Evan1204
 */
public class Fenetre_Plateau extends javax.swing.JFrame {
    PlateauDeJeu plateau;
    int x;
    int y;
    private int taillePlateau;
    /**
     * Creates new form Fenetre_Plateau
     */
    public Fenetre_Plateau() {
        initComponents();
        this.taillePlateau = 4;
        getContentPane().add(Panel_plateau, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, taillePlateau * 40, taillePlateau * 40));
        this.pack();
        this.revalidate();
        this.plateau = new PlateauDeJeu(taillePlateau);
        initialiserPartie();
        Panel_plateau.setLayout(new GridLayout(taillePlateau, taillePlateau));
        for (int x = 0; x < taillePlateau; x++) {
            for (int y = 0; y < taillePlateau; y++) {
                Tuiles_Graphique La_Tuile = new Tuiles_Graphique(plateau.matriceTuiles[x][y], 36, 36);
                Panel_plateau.add(La_Tuile); // ajout au Jpanel PanneauGrille
            }
        }
    }

    public void initialiserPartie(){
        Random random = new Random();
        plateau.Générer_Un_Deux_Trois(random.nextInt(3),random.nextInt(3),1);
        plateau.Générer_Un_Deux_Trois(random.nextInt(3),random.nextInt(3),2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_plateau = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_plateau.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout Panel_plateauLayout = new javax.swing.GroupLayout(Panel_plateau);
        Panel_plateau.setLayout(Panel_plateauLayout);
        Panel_plateauLayout.setHorizontalGroup(
            Panel_plateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Panel_plateauLayout.setVerticalGroup(
            Panel_plateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_plateau, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_Plateau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_plateau;
    // End of variables declaration//GEN-END:variables
}
