/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_threes;

import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Evan1204
 */
public class Fenêtre_de_Jeu extends javax.swing.JFrame {

    /**
     * Creates new form Fenêtre_de_Jeu
     */
    public Fenêtre_de_Jeu() {
        initComponents();
        
        Rien.setLayout(new GridLayout(1, 1));
        getContentPane().add(Rien, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 700,1, 1));
        
        MusiqueMaestro player = new MusiqueMaestro();
        String filePath = "musique\\Jack-Zankowski-Happy-Wheels-_Main-theme_.wav"; 
        player.play(filePath);
        Bienvenue.setLayout(new GridLayout( 1, 1));
        getContentPane().add(Bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(50,40,500,100));
        this.pack();
        this.revalidate();

        JLabel labelBienvenue = new JLabel("Bienvenue sur THREEEEES !");
        labelBienvenue.setFont(new Font("SansSerif", Font.BOLD, 24)); // Ajustez la police selon vos préférences
        labelBienvenue.setHorizontalAlignment(JLabel.CENTER); // Centre le texte horizontalement
        labelBienvenue.setVerticalAlignment(JLabel.CENTER); // Centre le texte verticalement
        Bienvenue.add(labelBienvenue);
        
        //Affiche un bouton facile vers la grille facile
        Jouer.setLayout(new GridLayout(1, 1));
        getContentPane().add(Jouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 40));
        this.pack();
        this.revalidate();

        JButton bouton_Jouer = new JButton("Facile");
        ActionListener ecouteurClick1 = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
            Fenetre_Plateau nouvelleFenetre = new Fenetre_Plateau();
            nouvelleFenetre.setVisible(true);
            player.stop(); //
            dispose();
            }
        };
        bouton_Jouer.addActionListener(ecouteurClick1);
        Jouer.add(bouton_Jouer);
    }

    /**     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Bienvenue = new javax.swing.JPanel();
        Jouer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Rien = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenue.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout BienvenueLayout = new javax.swing.GroupLayout(Bienvenue);
        Bienvenue.setLayout(BienvenueLayout);
        BienvenueLayout.setHorizontalGroup(
            BienvenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        BienvenueLayout.setVerticalGroup(
            BienvenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(Bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 30, 240, 80));

        Jouer.setText("jButton1");
        Jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JouerActionPerformed(evt);
            }
        });
        getContentPane().add(Jouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 40));

        javax.swing.GroupLayout RienLayout = new javax.swing.GroupLayout(Rien);
        Rien.setLayout(RienLayout);
        RienLayout.setHorizontalGroup(
            RienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        RienLayout.setVerticalGroup(
            RienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(Rien, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JouerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenêtre_de_Jeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bienvenue;
    private javax.swing.JButton Jouer;
    private javax.swing.JPanel Rien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
